import Head from "next/head";
import HomePage from "./home/HomePage";

export async function getStaticProps() {
  let response = await fetch(
    "https://itinder-api.azurewebsites.net/itinder/getstat"
  );
  let data = await response.json();
  return {
    props: {
      data: {
        stats: {
          candidates: data.candidatesCount,
          recruiters: data.recruitersCount,
        },
      },
    },
    revalidate: 1000,
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>ITinder</title>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}
